### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by liviubirau** [liviubirau/TakeMyOrder#4]
- [ ] Keep added foodItems/orders when rotation/configuration changed
- [ ] Use only strings
- [ ] Choose between EN or RO
- [ ] FAB Shared Element Transition to NewOrder activity
- [ ] Order Transition to NewOrder activity
- [ ] Allow different logins as in Inbox
- [ ] < API21 do nothing (or API19!?)
- [ ] Snackbar for different info (e.g. NoConnection...)
- [ ] Link to FB Page?
- [ ] Rotation problem in NewOrder activity
- [ ] Clear all warnings 
- [ ] CleanUp Code | remove comments...
